use core::{arch::asm, fmt::Display};

use crate::{
    arch::{
        except::{ArchExcept, ArchSyscallFrame, ArchTrapFrame, TrapCause},
        kcore::cpulocal::ArchCpuLocal,
        riscv64::csr,
        usermode::ArchUsermode,
    },
    except::generic_trap,
    kcore::sched::{Scheduler, Thread},
    misc::panic::unhandled_trap,
    process,
};

use super::{Riscv, RiscvRegfile};

unsafe extern "C" {
    pub fn riscv_exception_vector();
}

impl ArchExcept for Riscv {
    type SyscallFrame = RiscvExceptFrame;
    type TrapFrame = RiscvExceptFrame;

    #[inline(always)]
    fn enable_irq() {
        unsafe { asm!("csrs sstatus, {}", const csr::sstatus::SIE_MASK) };
    }

    #[inline(always)]
    fn disable_irq() {
        unsafe { asm!("csrc sstatus, {}", const csr::sstatus::SIE_MASK) };
    }

    #[inline(always)]
    fn get_irq_enabled() -> bool {
        let prev: usize;
        unsafe { asm!("csrr {}, sstatus", out(reg)prev) };
        prev & csr::sstatus::SIE_MASK != 0
    }

    #[inline(always)]
    fn enable_irq_if(cond: bool) {
        let mask = (cond as usize) << csr::sstatus::SIE_BIT;
        unsafe { asm!("csrs sstatus, {}", in(reg)mask) };
    }

    #[inline(always)]
    fn get_disable_irq() -> bool {
        let prev: usize;
        unsafe { asm!("csrrc {}, sstatus, {}", out(reg)prev, const csr::sstatus::SIE_MASK) };
        prev & csr::sstatus::SIE_MASK != 0
    }
}

#[repr(C)]
pub struct RiscvExceptFrame {
    pub regs: RiscvRegfile,
    // Fake frame pointer generated by the assembly for backtracing.
    pub fake_fp: *const (),
    // Other CSRs.
    pub sstatus: usize,
    pub scause: isize,
    pub stval: usize,
}

impl Display for RiscvExceptFrame {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "  PC  0x{:016x}  RA  0x{:016x}  SP  0x{:016x}  GP  0x{:016x}\n",
            self.regs.pc as usize, self.regs.ra, self.regs.sp, self.regs.gp,
        )?;
        write!(
            f,
            "  TP  0x{:016x}  T0  0x{:016x}  T1  0x{:016x}  T2  0x{:016x}\n",
            self.regs.tp, self.regs.t0, self.regs.t1, self.regs.t2,
        )?;
        write!(
            f,
            "  S0  0x{:016x}  S1  0x{:016x}  A0  0x{:016x}  A1  0x{:016x}\n",
            self.regs.s0, self.regs.s1, self.regs.a0, self.regs.a1,
        )?;
        write!(
            f,
            "  A2  0x{:016x}  A3  0x{:016x}  A4  0x{:016x}  A5  0x{:016x}\n",
            self.regs.a2, self.regs.a3, self.regs.a4, self.regs.a5,
        )?;
        write!(
            f,
            "  A6  0x{:016x}  A7  0x{:016x}  S2  0x{:016x}  S3  0x{:016x}\n",
            self.regs.a6, self.regs.a7, self.regs.s2, self.regs.s3,
        )?;
        write!(
            f,
            "  S4  0x{:016x}  S5  0x{:016x}  S6  0x{:016x}  S7  0x{:016x}\n",
            self.regs.s4, self.regs.s5, self.regs.s6, self.regs.s7,
        )?;
        write!(
            f,
            "  S8  0x{:016x}  S9  0x{:016x}  S10 0x{:016x}  S11 0x{:016x}\n",
            self.regs.s8, self.regs.s9, self.regs.s10, self.regs.s11,
        )?;
        write!(
            f,
            "  T3  0x{:016x}  T4  0x{:016x}  T5  0x{:016x}  T6  0x{:016x}\n",
            self.regs.t3, self.regs.t4, self.regs.t5, self.regs.t6,
        )?;
        write!(f, "  SSTATUS  0x{:016x}\n", self.sstatus)?;
        write!(f, "  SCAUSE   0x{:016x}\n", self.scause)?;
        write!(f, "  STVAL    0x{:016x}\n", self.stval)?;
        Ok(())
    }
}

impl ArchSyscallFrame for RiscvExceptFrame {
    fn set_retval(&mut self, value: usize) {
        self.regs.a0 = value;
    }
}

impl ArchTrapFrame for RiscvExceptFrame {
    fn is_kernel_mode(&self) -> bool {
        self.sstatus & csr::sstatus::SPP_MASK != 0
    }

    fn get_cause(&self) -> Option<TrapCause> {
        use csr::scause::*;
        match self.scause {
            IILLEGAL => Some(TrapCause::IllegalInsn),
            EBREAK => Some(TrapCause::Breakpoint),
            IPAGE => Some(TrapCause::PageFaultExec),
            LPAGE => Some(TrapCause::PageFaultLoad),
            SPAGE => Some(TrapCause::PageFaultStore),
            _ => None,
        }
    }

    fn get_name(&self) -> Option<&str> {
        use csr::scause::*;
        match self.scause {
            IALIGN => Some("Instruction address misaligned"),
            IACCESS => Some("Instruction access fault"),
            IILLEGAL => Some("Illegal instruction"),
            EBREAK => Some("Breakpoint"),
            LALIGN => Some("Load address misaligned"),
            LACCESS => Some("Load access fault"),
            SALIGN => Some("Store address misaligned"),
            SACCESS => Some("Store access fault"),
            ECALL_U => Some("E-call from U-mode"),
            ECALL_S => Some("E-call from S-mode"),
            IPAGE => Some("Instruction page fault"),
            LPAGE => Some("Load page fault"),
            SPAGE => Some("Store page fault"),
            SWCHECK => Some("Software check"),
            HWERR => Some("Hardware error"),
            _ => None,
        }
    }

    fn get_number(&self) -> usize {
        self.scause as usize
    }

    fn get_addr(&self) -> Option<usize> {
        use csr::scause::*;
        match self.scause {
            IILLEGAL | EBREAK | ECALL_U | ECALL_S => Some(self.regs.pc as _),
            IALIGN | IACCESS | LALIGN | LACCESS | SALIGN | SACCESS | IPAGE | LPAGE | SPAGE
            | HWERR => Some(self.stval),
            SWCHECK => Some(0),
            _ => None,
        }
    }

    fn get_pc(&self) -> *const () {
        self.regs.pc as _
    }

    fn noexc_skip(&mut self, addr: *const ()) {
        self.regs.pc = addr as _;
        self.regs.a0 = 1;
    }

    fn get_frame_ptr(&self) -> *const () {
        self.fake_fp
    }
}

#[unsafe(no_mangle)]
unsafe extern "C" fn riscv_exception_handler(frame: &mut RiscvExceptFrame) {
    if frame.scause < 0 && frame.scause & 0xff == 5 {
        // Timer interrupt.
        unsafe {
            (*Scheduler::get()).tick_interrupt(!frame.is_kernel_mode());
        }
        return;
    } else if frame.scause < 0 {
        // External or software interrupt.
        unsafe {
            // Low cause bits: 1 = supervisor software, 9 = supervisor external.
            let cause = (frame.scause as usize & 0xff) as u128;
            let cpulocal = &*Riscv::get_cpulocal();
            let mut handled = false;
            for ctl in &cpulocal.ext_irqctls {
                handled |= ctl.interrupt(cause);
            }
            if !handled {
                unhandled_trap(frame);
            }
        }
        return;
    } else if !frame.is_kernel_mode() && frame.scause == csr::scause::ECALL_U {
        process::syscall::dispatch(
            frame,
            frame.regs.a0,
            frame.regs.a1,
            frame.regs.a2,
            frame.regs.a3,
            frame.regs.a4,
            frame.regs.a5,
            frame.regs.a7,
        );
        return;
    } else {
        // TODO: Lazy-FPU init.
        generic_trap(frame);
    }

    unsafe {
        // Exit user-mode upon thread stop request.
        let current = Thread::current();
        if !current.is_null() && (*current).is_stopping() && !frame.is_kernel_mode() {
            Riscv::exit_usermode(&(*current).runtime().uctx);
        }
    }
}
