use core::{arch::asm, fmt::Display};

use crate::{
    arch::{
        except::{ArchExcept, ArchSyscallFrame, ArchTrapFrame, TrapCause},
        kcore::cpulocal::ArchCpuLocal,
        riscv64::csr,
    },
    bindings::log::LogLevel,
    except::generic_trap,
    kcore::sched::Scheduler,
    misc::panic::unhandled_trap,
};

use super::Riscv;

unsafe extern "C" {
    pub fn riscv_exception_vector();
}

impl ArchExcept for Riscv {
    type SyscallFrame = RiscvExceptFrame;
    type TrapFrame = RiscvExceptFrame;

    #[inline(always)]
    fn enable_irq() {
        unsafe { asm!("csrs sstatus, {}", const csr::sstatus::SIE_MASK) };
    }

    #[inline(always)]
    fn disable_irq() {
        unsafe { asm!("csrc sstatus, {}", const csr::sstatus::SIE_MASK) };
    }

    #[inline(always)]
    fn get_irq_enabled() -> bool {
        let prev: usize;
        unsafe { asm!("csrr {}, sstatus", out(reg)prev) };
        prev & csr::sstatus::SIE_MASK != 0
    }

    #[inline(always)]
    fn enable_irq_if(cond: bool) {
        let mask = (cond as usize) << csr::sstatus::SIE_BIT;
        unsafe { asm!("csrs sstatus, {}", in(reg)mask) };
    }

    #[inline(always)]
    fn get_disable_irq() -> bool {
        let prev: usize;
        unsafe { asm!("csrrc {}, sstatus, {}", out(reg)prev, const csr::sstatus::SIE_MASK) };
        prev & csr::sstatus::SIE_MASK != 0
    }
}

#[repr(C)]
pub struct RiscvExceptFrame {
    // Trapping instruction address.
    pub sepc: *const (),
    // GPRs x1 through x31 in order.
    pub ra: usize,
    pub sp: usize,
    pub gp: usize,
    pub tp: usize,
    pub t0: usize,
    pub t1: usize,
    pub t2: usize,
    pub s0: usize,
    pub s1: usize,
    pub a0: usize,
    pub a1: usize,
    pub a2: usize,
    pub a3: usize,
    pub a4: usize,
    pub a5: usize,
    pub a6: usize,
    pub a7: usize,
    pub s2: usize,
    pub s3: usize,
    pub s4: usize,
    pub s5: usize,
    pub s6: usize,
    pub s7: usize,
    pub s8: usize,
    pub s9: usize,
    pub s10: usize,
    pub s11: usize,
    pub t3: usize,
    pub t4: usize,
    pub t5: usize,
    pub t6: usize,
    // Fake frame pointer generated by the assembly for backtracing.
    pub fake_fp: *const (),
    // Other CSRs.
    pub sstatus: usize,
    pub scause: isize,
    pub stval: usize,
}

impl Display for RiscvExceptFrame {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "  PC  0x{:016x}  RA  0x{:016x}  SP  0x{:016x}  GP  0x{:016x}\n",
            self.sepc as usize, self.ra, self.sp, self.gp,
        )?;
        write!(
            f,
            "  TP  0x{:016x}  T0  0x{:016x}  T1  0x{:016x}  T2  0x{:016x}\n",
            self.tp, self.t0, self.t1, self.t2,
        )?;
        write!(
            f,
            "  S0  0x{:016x}  S1  0x{:016x}  A0  0x{:016x}  A1  0x{:016x}\n",
            self.s0, self.s1, self.a0, self.a1,
        )?;
        write!(
            f,
            "  A2  0x{:016x}  A3  0x{:016x}  A4  0x{:016x}  A5  0x{:016x}\n",
            self.a2, self.a3, self.a4, self.a5,
        )?;
        write!(
            f,
            "  A6  0x{:016x}  A7  0x{:016x}  S2  0x{:016x}  S3  0x{:016x}\n",
            self.a6, self.a7, self.s2, self.s3,
        )?;
        write!(
            f,
            "  S4  0x{:016x}  S5  0x{:016x}  S6  0x{:016x}  S7  0x{:016x}\n",
            self.s4, self.s5, self.s6, self.s7,
        )?;
        write!(
            f,
            "  S8  0x{:016x}  S9  0x{:016x}  S10 0x{:016x}  S11 0x{:016x}\n",
            self.s8, self.s9, self.s10, self.s11,
        )?;
        write!(
            f,
            "  T3  0x{:016x}  T4  0x{:016x}  T5  0x{:016x}  T6  0x{:016x}\n",
            self.t3, self.t4, self.t5, self.t6,
        )?;
        write!(f, "  SSTATUS  0x{:016x}\n", self.sstatus)?;
        write!(f, "  SCAUSE   0x{:016x}\n", self.scause)?;
        write!(f, "  STVAL    0x{:016x}\n", self.stval)?;
        Ok(())
    }
}

impl ArchSyscallFrame for RiscvExceptFrame {
    fn set_retval(&mut self, value: usize) {
        self.a0 = value;
    }
}

impl ArchTrapFrame for RiscvExceptFrame {
    fn is_kernel_mode(&self) -> bool {
        self.sstatus & 0x100 != 0
    }

    fn get_cause(&self) -> Option<TrapCause> {
        match self.scause {
            1 => Some(TrapCause::PageFaultExec),
            2 => Some(TrapCause::IllegalInsn),
            3 => Some(TrapCause::Breakpoint),
            5 => Some(TrapCause::PageFaultLoad),
            7 => Some(TrapCause::PageFaultStore),
            12 => Some(TrapCause::PageFaultExec),
            13 => Some(TrapCause::PageFaultLoad),
            15 => Some(TrapCause::PageFaultStore),
            _ => None,
        }
    }

    fn get_name(&self) -> Option<&str> {
        match self.scause {
            0 => Some("Instruction address misaligned"),
            1 => Some("Instruction access fault"),
            2 => Some("Illegal instruction"),
            3 => Some("Breakpoint"),
            4 => Some("Load address misaligned"),
            5 => Some("Load access fault"),
            6 => Some("Store address misaligned"),
            7 => Some("Store access fault"),
            8 => Some("E-call from U-mode"),
            9 => Some("E-call from S-mode"),
            12 => Some("Instruction page fault"),
            13 => Some("Load page fault"),
            15 => Some("Store page fault"),
            18 => Some("Software check"),
            19 => Some("Hardware error"),
            _ => None,
        }
    }

    fn get_number(&self) -> usize {
        self.scause as usize
    }

    fn get_addr(&self) -> Option<usize> {
        match self.scause {
            0 | 1 | 4 | 5 | 6 | 7 | 12 | 13 | 15 => Some(self.stval),
            2 | 3 => Some(self.sepc as usize),
            _ => None,
        }
    }

    fn get_pc(&self) -> *const () {
        self.sepc
    }

    fn noexc_skip(&mut self, addr: *const ()) {
        self.sepc = addr;
        self.a0 = 1;
    }

    fn get_frame_ptr(&self) -> *const () {
        self.fake_fp
    }
}

#[unsafe(no_mangle)]
unsafe extern "C" fn riscv_exception_handler(frame: &mut RiscvExceptFrame) {
    if frame.scause < 0 && frame.scause & 0xff == 5 {
        // Timer interrupt.
        unsafe {
            (*Scheduler::get()).tick_interrupt(!frame.is_kernel_mode());
        }
        return;
    } else if frame.scause < 0 {
        // External or software interrupt.
        unsafe {
            // Low cause bits: 1 = supervisor software, 9 = supervisor external.
            let cause = (frame.scause as usize & 0xff) as u128;
            let cpulocal = &*Riscv::get_cpulocal();
            let mut handled = false;
            for ctl in &cpulocal.ext_irqctls {
                handled |= ctl.interrupt(cause);
            }
            if !handled {
                unhandled_trap(frame);
            }
        }
        return;
    }

    // TODO: Lazy-FPU init.

    generic_trap(frame);
}
