use core::arch::{asm, naked_asm};

use crate::arch::{
    except::{ArchExcept, ArchSyscallFrame, ArchTrapFrame, TrapCause},
    riscv64::csr,
};

use super::Riscv;

impl ArchExcept for Riscv {
    type SyscallFrame = ExceptFrame;
    type TrapFrame = ExceptFrame;

    #[unsafe(naked)]
    extern "C" fn caller_frame_ptr() -> *const () {
        naked_asm!("mv a0, fp", "ret");
    }

    #[inline(always)]
    fn enable_irq() {
        unsafe { asm!("csrs sstatus, {}", const csr::sstatus::SIE_MASK) };
    }

    #[inline(always)]
    fn disable_irq() {
        unsafe { asm!("csrc sstatus, {}", const csr::sstatus::SIE_MASK) };
    }

    #[inline(always)]
    fn get_irq() -> bool {
        let prev: usize;
        unsafe { asm!("csrr {}, sstatus", out(reg)prev) };
        prev & csr::sstatus::SIE_MASK != 0
    }

    #[inline(always)]
    fn enable_irq_if(cond: bool) {
        let mask = (cond as usize) << csr::sstatus::SIE_BIT;
        unsafe { asm!("csrs sstatus, {}", in(reg)mask) };
    }

    #[inline(always)]
    fn get_disable_irq() -> bool {
        let prev: usize;
        unsafe { asm!("csrrc {}, sstatus, {}", out(reg)prev, const csr::sstatus::SIE_MASK) };
        prev & csr::sstatus::SIE_MASK != 0
    }
}

#[repr(C)]
pub struct ExceptFrame {
    // Trapping instruction address.
    pub sepc: *const (),
    // GPRs x1 through x31 in order.
    pub ra: usize,
    pub sp: usize,
    pub gp: usize,
    pub tp: usize,
    pub t0: usize,
    pub t1: usize,
    pub t2: usize,
    pub s0: usize,
    pub s1: usize,
    pub a0: usize,
    pub a1: usize,
    pub a2: usize,
    pub a3: usize,
    pub a4: usize,
    pub a5: usize,
    pub a6: usize,
    pub a7: usize,
    pub s2: usize,
    pub s3: usize,
    pub s4: usize,
    pub s5: usize,
    pub s6: usize,
    pub s7: usize,
    pub s8: usize,
    pub s9: usize,
    pub s10: usize,
    pub s11: usize,
    pub t3: usize,
    pub t4: usize,
    pub t5: usize,
    pub t6: usize,
    // Fake frame pointer generated by the assembly for backtracing.
    pub fake_fp: *const (),
    // Other CSRs.
    pub sstatus: usize,
    pub scause: usize,
    pub stval: usize,
}

impl ArchSyscallFrame for ExceptFrame {
    fn set_retval(&mut self, value: usize) {
        self.a0 = value;
    }
}

impl ArchTrapFrame for ExceptFrame {
    fn is_kernel_mode(&self) -> bool {
        self.sstatus & 0x100 != 0
    }

    fn get_cause(&self) -> (Option<TrapCause>, usize) {
        let cause = match self.scause {
            1 => Some(TrapCause::PageFaultExec),
            2 => Some(TrapCause::IllegalInsn),
            3 => Some(TrapCause::Breakpoint),
            5 => Some(TrapCause::PageFaultLoad),
            7 => Some(TrapCause::PageFaultStore),
            12 => Some(TrapCause::PageFaultExec),
            13 => Some(TrapCause::PageFaultLoad),
            15 => Some(TrapCause::PageFaultStore),
            _ => None,
        };
        (cause, self.scause)
    }

    fn get_pc(&self) -> *const () {
        self.sepc
    }

    fn get_frame_ptr(&self) -> *const () {
        self.fake_fp
    }
}
